# docker-compose.yml
version: '3.1'
services:
  prometheus:
    build:
      context: ../
      dockerfile: ./docker/prometheus/dockerfile
    container_name: "prometheus"
    hostname: "prometheus"
    ports:
      - "9090:9090"
    links:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    networks:
      - axon-net

  grafana:
    build:
      context: ../
      dockerfile: ./docker/grafana/dockerfile
    image: grafana/grafana
    container_name: "grafana"
    hostname: "grafana"
    ports:
      - "3000:3000"
    links:
      - prometheus
    networks:
      - axon-net

  demo-app-1:
    image:  demo-app:0.1.0-SNAPSHOT
    depends_on:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver-enterprise-1:8124,axonserver-enterprise-2:8125,axonserver-enterprise-3:8126
      - SERVER_PORT=8080
      - MANAGEMENT_SERVER_PORT=8081
    links:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - axon-net


  demo-app-2:
    image: demo-app:0.1.0-SNAPSHOT
    depends_on:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver-enterprise-1:8124,axonserver-enterprise-2:8125,axonserver-enterprise-3:8126
      - SERVER_PORT=8082
      - MANAGEMENT_SERVER_PORT=8083
    links:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    ports:
      - 8082:8082
      - 8083:8083
    networks:
      - axon-net

  axonserver-enterprise-1:
    image: eu.gcr.io/axoniq-devops/axonserver-enterprise:4.5
    hostname: axonserver-enterprise-1
    environment:
      - AXONIQ_AXONSERVER_CLUSTERTEMPLATE_PATH=/config/cluster-template.yml
      - AXONIQ_LICENSE=/config/axoniq.license
      - AXONIQ_AXONSERVER_EVENT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_SNAPSHOT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_CONTROLDB-PATH=/controldb
      - AXONIQ_AXONSERVER_REPLICATION_LOG-STORAGE-FOLDER=/raft-log
      - AXONIQ_AXONSERVER_NAME=axonserver-enterprise-1
      - AXONIQ_AXONSERVER_HOSTNAME=axonserver-enterprise-1
      - SERVER_PORT=8024
      - AXONIQ_AXONSERVER_PORT=8124
      - AXONIQ_AXONSERVER_REPLICATION_FLOW-BUFFER=50
      - AXONIQ_AXONSERVER_REPLICATION_MAX-SNAPSHOT-CHUNKS-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_MAX-ENTRIES-PER-BATCH=10
      - LOGGING_FILE=/axon-server-logs/axonserver-enterprise-1.log
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - ./config:/config
      - axonserver-enterprise-1-log:/raft-log
      - axonserver-enterprise-1-eventstore:/eventstorage
      - axonserver-enterprise-1-controldb:/controldb
      - axonserver-logs:/axon-server-logs
      - axonserver-enterprise-1-security:/security
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-net

  axonserver-enterprise-2:
    image: eu.gcr.io/axoniq-devops/axonserver-enterprise:4.5
    hostname: axonserver-enterprise-2
    environment:
      - AXONIQ_AXONSERVER_CLUSTERTEMPLATE_PATH=/config/cluster-template.yml
      - AXONIQ_LICENSE=/config/axoniq.license
      - AXONIQ_AXONSERVER_EVENT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_SNAPSHOT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_CONTROLDB-PATH=/controldb
      - AXONIQ_AXONSERVER_NAME=axonserver-enterprise-2
      - AXONIQ_AXONSERVER_HOSTNAME=axonserver-enterprise-2
      - SERVER_PORT=8025
      - AXONIQ_AXONSERVER_PORT=8125
      - AXONIQ_AXONSERVER_REPLICATION_FLOW-BUFFER=50
      - AXONIQ_AXONSERVER_REPLICATION_MAX-SNAPSHOT-CHUNKS-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_MAX-ENTRIES-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_LOG-STORAGE-FOLDER=/raft-log
      - LOGGING_FILE=/axon-server-logs/axonserver-enterprise-2.log
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - ./config:/config
      - axonserver-enterprise-2-log:/raft-log
      - axonserver-enterprise-2-eventstore:/eventstorage
      - axonserver-enterprise-2-controldb:/controldb
      - axonserver-logs:/axon-server-logs
      - axonserver-enterprise-2-security:/security
    ports:
      - '8025:8025'
      - '8125:8125'
      - '8225:8225'
    networks:
      - axon-net

  axonserver-enterprise-3:
    image: eu.gcr.io/axoniq-devops/axonserver-enterprise:4.5
    hostname: axonserver-enterprise-3
    environment:
      - AXONIQ_AXONSERVER_CLUSTERTEMPLATE_PATH=/config/cluster-template.yml
      - AXONIQ_LICENSE=/config/axoniq.license
      - AXONIQ_AXONSERVER_EVENT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_SNAPSHOT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_CONTROLDB-PATH=/controldb
      - AXONIQ_AXONSERVER_NAME=axonserver-enterprise-3
      - AXONIQ_AXONSERVER_HOSTNAME=axonserver-enterprise-3
      - SERVER_PORT=8026
      - AXONIQ_AXONSERVER_PORT=8126
      - AXONIQ_AXONSERVER_REPLICATION_FLOW-BUFFER=50
      - AXONIQ_AXONSERVER_REPLICATION_MAX-SNAPSHOT-CHUNKS-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_MAX-ENTRIES-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_LOG-STORAGE-FOLDER=/raft-log
      - LOGGING_FILE=/axon-server-logs/axonserver-enterprise-3.log
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - ./config:/config
      - axonserver-enterprise-3-log:/raft-log
      - axonserver-enterprise-3-eventstore:/eventstorage
      - axonserver-enterprise-3-controldb:/controldb
      - axonserver-logs:/axon-server-logs
      - axonserver-enterprise-3-security:/security
    ports:
      - '8026:8026'
      - '8126:8126'
      - '8226:8226'
    networks:
      - axon-net


volumes:
  axonserver-enterprise-1-log:
  axonserver-enterprise-1-eventstore:
  axonserver-enterprise-1-controldb:
  axonserver-enterprise-2-log:
  axonserver-enterprise-2-eventstore:
  axonserver-enterprise-2-controldb:
  axonserver-enterprise-3-log:
  axonserver-enterprise-3-eventstore:
  axonserver-enterprise-3-controldb:
  axonserver-logs:
  axonserver-enterprise-1-security:
  axonserver-enterprise-2-security:
  axonserver-enterprise-3-security:

networks:
  axon-net: